# config_train.py

# ==============================================================================
# 1. DeepMD 训练配置模板 (input.json)
# ==============================================================================
DEEPMD_TEMPLATE = {
    "_comment": "DeepMD configuration generated by HONPAS-MLP Platform",
    "model": {
        # "type_map": [],  <-- 脚本自动填充
        "descriptor": {
            "type": "se_e2_a",
            "sel": "auto",
            "rcut_smth": 0.50,
            "rcut": 6.00,
            "neuron": [25, 50, 100],
            "resnet_dt": False,
            "axis_neuron": 16,
            "seed": 1
        },
        "fitting_net": {
            "neuron": [240, 240, 240],
            "resnet_dt": True,
            "seed": 10
        }
    },
    "learning_rate": {
        "type": "exp",
        "decay_steps": 5000,
        "start_lr": 0.001,
        "stop_lr": 3.51e-8
    },
    "loss": {
        "type": "ener",
        "start_pref_e": 0.02, "limit_pref_e": 1,
        "start_pref_f": 1000, "limit_pref_f": 1,
        "start_pref_v": 0,    "limit_pref_v": 0
    },
    "training": {
        # "training_data": ..., <-- 脚本自动填充
        # "validation_data": ..., <-- 脚本自动填充
        "numb_steps": 200000,
        "seed": 10,
        "disp_file": "lcurve.out",
        "disp_freq": 100,
        "save_freq": 1000,
        "save_ckpt": "model.ckpt"
    }
}

# ==============================================================================
# 2. GPUMD (NEP) 训练配置模板 (nep.in)
# ==============================================================================
GPUMD_NEP_TEMPLATE = {
    "version":       4,       # NEP 版本
    "cutoff":        "8 4",   # 径向截断 8.0, 角向截断 4.0
    "n_max":         "4 4",   # 径向基函数个数
    "basis_size":    "8 8",   # 
    "l_max":         "4 2 0", # 角向阶数
    "neuron":        30,      # 隐藏层神经元
    "lambda_e":      1.0,     # 能量权重
    "lambda_f":      1.0,     # 力权重
    "lambda_v":      0.1,     # 维里权重
    "batch":         1000,    # 批大小
    "population":    50,      # 种群大小 
    "generation":    100000   # 训练步数
}